// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwmwcuOIa2VMGZur9UzA9S5f_xY6B5oTE',
    appId: '1:621885739649:web:943d4c3e61f6ea6f573380',
    messagingSenderId: '621885739649',
    projectId: 'media-367d6',
    authDomain: 'media-367d6.firebaseapp.com',
    storageBucket: 'media-367d6.appspot.com',
    measurementId: 'G-Y3K08MGY06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-TmkdpgD__NsMrCi-TmNq9OxbiPKD8pU',
    appId: '1:621885739649:android:f1d45f31a4895515573380',
    messagingSenderId: '621885739649',
    projectId: 'media-367d6',
    storageBucket: 'media-367d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeEahiu8r4xaeCGw4OKlDXZ-Vm18BQ79U',
    appId: '1:621885739649:ios:d7bc5f0dd9b02e4c573380',
    messagingSenderId: '621885739649',
    projectId: 'media-367d6',
    storageBucket: 'media-367d6.appspot.com',
    androidClientId: '621885739649-69gvlvnkltlndtl4u0fc3l8rd914kha4.apps.googleusercontent.com',
    iosClientId: '621885739649-m6a8pfdavuqgjtn7i77kk752rdn1kfqa.apps.googleusercontent.com',
    iosBundleId: 'com.sihive.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeEahiu8r4xaeCGw4OKlDXZ-Vm18BQ79U',
    appId: '1:621885739649:ios:d7bc5f0dd9b02e4c573380',
    messagingSenderId: '621885739649',
    projectId: 'media-367d6',
    storageBucket: 'media-367d6.appspot.com',
    androidClientId: '621885739649-69gvlvnkltlndtl4u0fc3l8rd914kha4.apps.googleusercontent.com',
    iosClientId: '621885739649-m6a8pfdavuqgjtn7i77kk752rdn1kfqa.apps.googleusercontent.com',
    iosBundleId: 'com.sihive.flutterApp',
  );
}
